#PACE: Start of Constraints generated by PACE


#PACE: Start of PACE I/O Pin Assignments
#NET "clk"  LOC = E3	| IOSTANDARD = LVCMOS33; 
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { CLK }]; #IO_L12P_T1_MRCC_35 Sch=clk100mhz
#NET "enable"  LOC=J15 | IOSTANDARD=LVCMOS33; 
#NET "input"  LOC=L16 | IOSTANDARD=LVCMOS33; 
#NET "reset"  LOC=M13 | IOSTANDARD=LVCMOS33; 

set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { RESET }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS33 } [get_ports { STARTA }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property -dict { PACKAGE_PIN M13   IOSTANDARD LVCMOS33 } [get_ports { LOADB }]; #IO_L24N_T3_RS0_15 Sch=sw[0]

set_property -dict { PACKAGE_PIN P17   IOSTANDARD LVCMOS33 } [get_ports { A }]; #IO_L24N_T3_RS0_15 Sch=sw[0]

set_property -dict { PACKAGE_PIN H6   IOSTANDARD LVCMOS33 } [get_ports { B[0]}]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property -dict { PACKAGE_PIN U12   IOSTANDARD LVCMOS33 } [get_ports { B[1]}]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property -dict { PACKAGE_PIN U11   IOSTANDARD LVCMOS33 } [get_ports { B[2]}]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property -dict { PACKAGE_PIN V10   IOSTANDARD LVCMOS33 } [get_ports { B[3]}]; #IO_L24N_T3_RS0_15 Sch=sw[0]


#set_property -dict { PACKAGE_PIN R16   IOSTANDARD LVCMOS33 } [get_ports { request }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
#set_property -dict { PACKAGE_PIN T13   IOSTANDARD LVCMOS33 } [get_ports { one_tl }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
#set_property -dict { PACKAGE_PIN H6   IOSTANDARD LVCMOS33 } [get_ports { take_item }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
#set_property -dict { PACKAGE_PIN U12   IOSTANDARD LVCMOS33 } [get_ports { reset_async }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]

set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { STARTC }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { C }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]

set_property -dict { PACKAGE_PIN V11   IOSTANDARD LVCMOS33 } [get_ports {             clock_seysi  }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports {             input_accepted  }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]


#NET "led_next<0>"  LOC=H17 | IOSTANDARD=LVCMOS33;
#NET "led_next<1>"  LOC=K15 | IOSTANDARD=LVCMOS33; 
#NET "led_next<2>"  LOC=J13 | IOSTANDARD=LVCMOS33;
#NET "led_next<3>"  LOC=N14 | IOSTANDARD=LVCMOS33;
#NET "led_next<4>"  LOC=R18 | IOSTANDARD=LVCMOS33; 
#NET "led_next<5>"  LOC=V17 | IOSTANDARD=LVCMOS33;
#NET "led_next<6>"  LOC=U17 | IOSTANDARD=LVCMOS33;
#NET "led_next<7>"  LOC=U16 | IOSTANDARD=LVCMOS33;

#NET "seg_out<0>"  LOC=H15 | IOSTANDARD=LVCMOS33;
#NET "seg_out<1>"  LOC=T10 | IOSTANDARD=LVCMOS33; 
#NET "seg_out<2>"  LOC=R10 | IOSTANDARD=LVCMOS33;
#NET "seg_out<3>"  LOC=K16 | IOSTANDARD=LVCMOS33;
#NET "seg_out<4>"  LOC=K13 | IOSTANDARD=LVCMOS33; 
#NET "seg_out<5>"  LOC=P15 | IOSTANDARD=LVCMOS33;
#NET "seg_out<6>"  LOC=T11 | IOSTANDARD=LVCMOS33;
#NET "seg_out<7>"  LOC=L18 | IOSTANDARD=LVCMOS33;


#NET "seg_sel<0>"  LOC=J17 | IOSTANDARD=LVCMOS33; 
#NET "seg_sel<1>"  LOC=J18 | IOSTANDARD=LVCMOS33;
#NET "seg_sel<2>"  LOC=T9 | IOSTANDARD=LVCMOS33; 
#NET "seg_sel<3>"  LOC=J14 | IOSTANDARD=LVCMOS33; 
#NET "seg_sel<4>"  LOC=P14 | IOSTANDARD=LVCMOS33; 
#NET "seg_sel<5>"  LOC=T14 | IOSTANDARD=LVCMOS33; 
#NET "seg_sel<6>"  LOC=K2 | IOSTANDARD=LVCMOS33; 
#NET "seg_sel<7>"  LOC=U13 | IOSTANDARD=LVCMOS33; 


#PACE: Start of PACE Area Constraints

#PACE: Start of PACE Prohibit Constraints

#PACE: End of Constraints generated by PACE